### ISSUE TITLE
Compatability with sasview custom plugin models

### ISSUE THREAD

**Issue by brendenpelkie** [BAMresearch/McSAS3#14]
I am running into an error when trying to fit a sasview custom plugin model with McSAS 3. Ultimately what I am trying to do is fit a linear combination of fractal + sphere models. If there is a better way of doing this in McSAS that avoids this error that would also resolve my problem.

The problem: Using a custom sasview plugin model leads to a NotImplementedError during model kernel evalution.

Steps to reproduce: 

1. Generate a sasview plugin model using the GUI tool. The resulting .py file: 

```from sasmodels.core import load_model_info
from sasmodels.sasview_model import make_model_from_info

model_info = load_model_info('sphere+fractal')
model_info.name = 'fractal_sphere'
model_info.description = 'fractal + sphere'
Model = make_model_from_info(model_info)
```

2. Copy this file into the `models` directory of the relevant sasmodels installation.

3. Update the run config file to call this model with correct parameters: 

```
modelName: "fractal_sphere"
nContrib: 300
modelDType: "default"
fitParameterLimits:
  A_scale: 'auto'
  A_radius: 'auto'
  B_scale: 'auto'
  B_radius: 'auto'
  B_fractal_dim: 
    - 1
    - 3
  B_cor_length: 'auto'
  B_volfraction: 'auto'
staticParameters:
  A_sld: 8.575 # units of 1e-6 A^-2
  A_sld_solvent: 9.469
  B_sld_block: 8.575
  B_sld_solvent: 9.469
maxIter: 1000
convCrit: 1
nRep: 3
nCores: 5
```

4. Run the fit (imports and filepath definitions omitted): 
```
with open(read_config_fp, "r") as f:
    readDict = yaml.safe_load(f)
# load the data
mds = McData1D.McData1D(filename=dataFile, resultIndex=resultIndex, **readDict)
# store the full data in the result file:
mds.store(result_file)
# read the configuration file
with open(run_config_fp, "r") as f:
    optDict = yaml.safe_load(f)
if n_threads > 0:
    optDict["nCores"] = n_threads
# run the Monte Carlo method
mh = McHat.McHat(seed=None, resultIndex=resultIndex, **optDict)
md = mds.measData.copy()
mh.run(md, result_file, resultIndex = resultIndex)

```

Resulting stack trace: 

```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "[/Users/bgpelkie/miniconda3/envs/mcsas/lib/python3.11/multiprocessing/pool.py", line 125](http://localhost:8888/Users/bgpelkie/miniconda3/envs/mcsas/lib/python3.11/multiprocessing/pool.py#line=124), in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "[/Users/bgpelkie/miniconda3/envs/mcsas/lib/python3.11/multiprocessing/pool.py", line 51](http://localhost:8888/Users/bgpelkie/miniconda3/envs/mcsas/lib/python3.11/multiprocessing/pool.py#line=50), in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/bgpelkie/Code/McSAS3/src/mcsas3/McHat.py", line 150](http://localhost:8888/Users/bgpelkie/Code/McSAS3/src/mcsas3/McHat.py#line=149), in runOnce
    mc = McCore(measData, model=self._model, opt=self._opt, resultIndex=resultIndex)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/bgpelkie/Code/McSAS3/src/mcsas3/mccore.py", line 92](http://localhost:8888/Users/bgpelkie/Code/McSAS3/src/mcsas3/mccore.py#line=91), in __init__
    self.initModelI()
  File "[/Users/bgpelkie/Code/McSAS3/src/mcsas3/mccore.py", line 127](http://localhost:8888/Users/bgpelkie/Code/McSAS3/src/mcsas3/mccore.py#line=126), in initModelI
    I, V = self._model.calcModelIV(self._model.parameterSet.loc[0].to_dict())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/bgpelkie/Code/McSAS3/src/mcsas3/mcmodel.py", line 382](http://localhost:8888/Users/bgpelkie/Code/McSAS3/src/mcsas3/mcmodel.py#line=381), in calcModelIV
    F, Fsq, R_eff, V_shell, V_ratio = sasmodels.direct_model.call_Fq(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/bgpelkie/miniconda3/envs/mcsas/lib/python3.11/site-packages/sasmodels/direct_model.py", line 81](http://localhost:8888/Users/bgpelkie/miniconda3/envs/mcsas/lib/python3.11/site-packages/sasmodels/direct_model.py#line=80), in call_Fq
    return calculator.Fq(call_details, values, cutoff, is_magnetic, R_eff_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/bgpelkie/miniconda3/envs/mcsas/lib/python3.11/site-packages/sasmodels/kernel.py", line 182](http://localhost:8888/Users/bgpelkie/miniconda3/envs/mcsas/lib/python3.11/site-packages/sasmodels/kernel.py#line=181), in Fq
    self._call_kernel(call_details, values, cutoff, magnetic,
  File "[/Users/bgpelkie/miniconda3/envs/mcsas/lib/python3.11/site-packages/sasmodels/kernel.py", line 218](http://localhost:8888/Users/bgpelkie/miniconda3/envs/mcsas/lib/python3.11/site-packages/sasmodels/kernel.py#line=217), in _call_kernel
    raise NotImplementedError()
NotImplementedError
"""

The above exception was the direct cause of the following exception:

NotImplementedError                       Traceback (most recent call last)
Cell In[29], line 24
     22 mh = McHat.McHat(seed=None, resultIndex=resultIndex, **optDict)
     23 md = mds.measData.copy()
---> 24 mh.run(md, result_file, resultIndex = resultIndex)
     25 break

File [~/Code/McSAS3/src/mcsas3/McHat.py:116](http://localhost:8888/lab/workspaces/auto-o/tree/APS_data_analysis/mcsas_fit/~/Code/McSAS3/src/mcsas3/McHat.py#line=115), in McHat.run(self, measData, filename, resultIndex)
    114 pool = multiprocessing.Pool(self.nCores, initializer=initStoreLock, initargs=(lock,))
    115 runArgs = [(measData, filename, r, True, resultIndex) for r in range(self.nRep)]
--> 116 outputs = pool.starmap(self.runOnce, runArgs)
    117 pool.close()
    118 pool.join()

File [~/miniconda3/envs/mcsas/lib/python3.11/multiprocessing/pool.py:375](http://localhost:8888/lab/workspaces/auto-o/tree/APS_data_analysis/mcsas_fit/~/miniconda3/envs/mcsas/lib/python3.11/multiprocessing/pool.py#line=374), in Pool.starmap(self, func, iterable, chunksize)
    369 def starmap(self, func, iterable, chunksize=None):
    370     '''
    371     Like `map()` method but the elements of the `iterable` are expected to
    372     be iterables as well and will be unpacked as arguments. Hence
    373     `func` and (a, b) becomes func(a, b).
    374     '''
--> 375     return self._map_async(func, iterable, starmapstar, chunksize).get()

File [~/miniconda3/envs/mcsas/lib/python3.11/multiprocessing/pool.py:774](http://localhost:8888/lab/workspaces/auto-o/tree/APS_data_analysis/mcsas_fit/~/miniconda3/envs/mcsas/lib/python3.11/multiprocessing/pool.py#line=773), in ApplyResult.get(self, timeout)
    772     return self._value
    773 else:
--> 774     raise self._value

NotImplementedError:
```

**Comment by toqduj** [comment]
Hi @brendenpelkie, 

That was a good effort. 

It will be clearer in the upcoming GUI (McSAS3GUI: https://github.com/toqduj/McSAS3GUI), but McSAS3 will directly generate the combined models by itself. It will strip the A_scale and B_scale. 

Also, be careful with setting more than one value to "auto", as it will very quickly generate non-unique solutions. Start with one. In particular, you will find that with volume fraction and size distribution as explained here: https://lookingatnothing.com/index.php/archives/3323

So you can get what you want by changing your run config model name to: 
```yaml
modelName: sphere+fractal
nContrib: 300
modelDType: default
fitParameterLimits:
  A_radius: 25 # example
  B_radius: auto
  B_fractal_dim: 3
  B_cor_length: 26 # ibid
  B_volfraction: 0.2 # it is not possible to get both a unique volume fraction and size distribution!
staticParameters:
  A_sld: 8.575 # units of 1e-6 A^-2
  A_sld_solvent: 9.469
  B_sld_block: 8.575
  B_sld_solvent: 9.469
maxIter: 1000
convCrit: 1
nRep: 3
nCores: 5
```

let me know if it doesn't work and I'll play around with your data and the settings until it does..

**Comment by brendenpelkie** [comment]
Thanks for the help. I'm still getting the same issue with your updated run config. Here's an example notebook with config and data files to reproduce: https://github.com/pozzo-research-group/silica-np-synthesis/blob/main/APS_data_analysis/mcsas_fit/McSAS3_combinedmodel_debug/run_config_brian.yaml. This is with the current `main` branch of McSAS3. Let me know if there are any other useful details to reproduce.

**Comment by toqduj** [comment]
Ok, I've had some time to look into this... seems I did not include support for sasmodels' mixture types (e.g. a+b+c. It can do product types like sphere@hardsphere or sphere*fractal). 

At first I thought this was a bug so I started modifying it to accept these mixture types for contributions... and ran into a problem: to get the scaling right, I need to have a volume of each individual contribution. mixture types do not seem to output a volume for the entire model (nor is it possible to determine a volume for models like power_law or fractal). 

So, it seems this is a more fundamental problem with the use of mixture types rather than a straightforward bug. This will require some thought on how to implement this. it might require one to put in a custom volume function eventually. I'll contact Paul Kienzle to ask if he has ideas. 

That said, a sphere+fractal behaviour can be modelled by pure spheres themselves. The fractal behaviour will be represented as a uniform or sloped size distribution (depending on the fractal dimension), spanning the entire size range. I had a quick go at your data, and it looked like there might be some structure factor in the data. Though I have no idea what the rest of your data looks like, I can recommend settings like these: 

for the data loading:
```yaml
nbins: 100
dataRange: [0.003, 0.5]
csvargs:
  sep: \s+
  skiprows: 1
  header: null
  names: [Q, I, ISigma]
```

and the optimization:
```yaml
modelName: sphere@hardsphere
nContrib: 300
modelDType: default
fitParameterLimits:
  radius: auto
staticParameters:
  sld: 33.4
  sld_solvent: 0
  volfraction: 0.05
  structure_factor_mode: 1
  radius_effective_mode: 1
maxIter: 50000
maxAccept: 1500
convCrit: 1
nRep: 10
nCores: 5
```

Also, if you want to quickly explore models and model combinations, SasModelsExplorer (https://github.com/bamresearch/sasmodelsexplorer) does support a wider range of sasmodels combinations, including sphere+fractal and polydispersity.
